server:
  port: ${port:56010}

spring:
  application:
    name: quickstart-provider
  cloud:
    nacos:
      discovery:
        server-addr: 49.235.125.139:8848
        namespace: b6cb281f-df22-4f43-9048-ff16ebcdec65
logging:
  level:
    root: info
    org.springframework: info